#ifndef LWSC_CTX_H
#define LWSC_CTX_H

typedef enum {
	LWSC_CTX_NO_CONTEXT,
	LWSC_CTX_MISSING_OBJECT,
	LWSC_CTX_EMPTY_PAREN,
	LWSC_CTX_MULTI_SEPARATORS,
	LWSC_CTX_UNKNOWN_OBJECT,
	LWSC_CTX_COUNT
} lwsc_ctx_id;

extern const char *lwsc_ctx[LWSC_CTX_COUNT];

#endif