#ifndef LWSC_CTX_H
#define LWSC_CTX_H

typedef enum {
	LWSC_CTX_MISSING_MANTISSA,
	LWSC_CTX_MISSING_OPERATOR,
	LWSC_CTX_MISSING_OPERAND,
	LWSC_CTX_MISSING_CLOSE_PAREN,
	LWSC_CTX_MISSING_OPEN_PAREN,
	LWSC_CTX_EMPTY_PAREN,
	LWSC_CTX_MULTI_SEPARATORS,
	LWSC_CTX_FN_NO_PARAN,
	LWSC_CTX_FN_NOT_DEFINED,
	LWSC_CTX_OP_NO_DEFINED,
	LWSC_CTX_VAR_NOT_DEFINED,
	LWSC_CTX_COUNT,
} lwsc_ctx_id;

extern const char *lwsc_ctx[LWSC_CTX_COUNT];

#endif