#ifndef LWSC_MSG_H
#define LWSC_MSG_H

typedef enum {
	LWSC_MSG_UNBALANCED_PAREN,
	LWSC_MSG_INVALID_NUMBER,
	LWSC_MSG_INVALID_EXPR,
	LWSC_MSG_UNKNOWN_OPERATOR,
	LWSC_MSG_UNKNOWN_OPERAND,
	LWSC_MSG_UNKNOWN_FUNCTION,
	LWSC_MSG_COUNT,
} lwsc_msg_id;

extern const char *lwsc_msg[LWSC_MSG_COUNT];

#endif