#ifndef LWSC_MSG_H
#define LWSC_MSG_H

typedef enum {
	LWSC_MSG_NO_MESSAGE,
	LWSC_MSG_INVALID_EXPRESSION,
	LWSC_MSG_UNKNOWN_OBJECT,
	LWSC_MSG_NO_MEMORY,
	LWSC_MSG_HPT_OVERFLOW,
	LWSC_MSG_UNAVALIABLE_HEADER,
	LWSC_MSG_COUNT,
} lwsc_msg_id;

extern const char *lwsc_msg[LWSC_MSG_COUNT];

#endif